import io
import logging

import io
import logging

try:
    from weasyprint import HTML, CSS
    WEASYPRINT_INSTALLED = True
except Exception:
    WEASYPRINT_INSTALLED = False

logger = logging.getLogger('ats_resume_scorer')

def generate_combined_pdf(html_docs: dict[str, str], data: dict = None) -> bytes:
    if WEASYPRINT_INSTALLED:
        try:
            documents = []
            for name, html_str in html_docs.items():
                doc = HTML(string=html_str).render()
                documents.append(doc)
            
            first_doc = documents[0]
            for other_doc in documents[1:]:
                for page in other_doc.pages:
                    first_doc.pages.append(page)
                    
            return first_doc.write_pdf()
        except Exception as e:
            logger.warning(f"WeasyPrint failed ({e}), falling back to ReportLab...")

    # Enhanced ReportLab PDF Generation
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#0f172a"),
        fontName="Helvetica-Bold",
        spaceAfter=4
    )
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#64748b"),
        fontName="Helvetica",
        spaceAfter=14
    )
    h2_style = ParagraphStyle(
        'Heading2Custom',
        parent=styles['Heading2'],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#0f172a"),
        fontName="Helvetica-Bold",
        spaceBefore=14,
        spaceAfter=8
    )
    body_style = ParagraphStyle(
        'BodyCustom',
        parent=styles['Normal'],
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor("#334155"),
        fontName="Helvetica"
    )
    bold_body = ParagraphStyle(
        'BoldBody',
        parent=body_style,
        fontName="Helvetica-Bold",
        textColor=colors.HexColor("#0f172a")
    )
    fix_style = ParagraphStyle(
        'FixBody',
        parent=body_style,
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#047857"),
        spaceBefore=3
    )

    story = []
    
    # 1. Header & Title Banner
    story.append(Paragraph("Resumely — Formal ATS Resume Audit Report", title_style))
    story.append(Paragraph("Generated by Resumely AI ATS Engine | Multi-Dimensional Candidate Evaluation", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"), spaceAfter=14))

    if data:
        score = round(data.get('ats_score') or data.get('ATS_score', 0))
        interp = data.get('interpretation', 'Evaluation complete.')

        # 2. Executive Score Banner Box
        score_bg = colors.HexColor("#ecfdf5") if score >= 80 else colors.HexColor("#fffbeb") if score >= 60 else colors.HexColor("#fef2f2")
        score_text_color = colors.HexColor("#047857") if score >= 80 else colors.HexColor("#b45309") if score >= 60 else colors.HexColor("#b91c1c")

        banner_data = [
            [
                Paragraph(f"<font size=28 color='{score_text_color.hexval()}'><b>{score}</b></font><font size=14 color='#64748b'>/100</font>", body_style),
                Paragraph(f"<b>Overall ATS Score Assessment</b><br/>{interp}", body_style)
            ]
        ]
        banner_table = Table(banner_data, colWidths=[110, 430])
        banner_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), score_bg),
            ('ALIGN', (0, 0), (0, 0), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
        ]))
        story.append(banner_table)
        story.append(Spacer(1, 14))

        # 3. Component Weight Breakdown Table
        cs = data.get('component_scores', {})
        if hasattr(cs, '__dict__'):
            cs = cs.__dict__
        if isinstance(cs, dict) and cs:
            story.append(Paragraph("1. Component Score Breakdown", h2_style))
            
            comp_weights = [
                ("Formatting Quality", cs.get("formatting", 0), 20),
                ("Keywords & Skills Match", cs.get("keywords", 0), 25),
                ("Content & Action Verbs", cs.get("content", 0), 25),
                ("Skill Experience Validation", cs.get("skill_validation", 0), 15),
                ("ATS Reader Compatibility", cs.get("ats_compatibility", 0), 15),
            ]

            table_data = [["Scoring Category", "Earned Points", "Max Weight", "Status"]]
            for label, val, max_w in comp_weights:
                pct = (val / max_w) * 100 if max_w else 0
                status_str = "Strong" if pct >= 80 else "Moderate" if pct >= 60 else "Needs Work"
                table_data.append([label, f"{val:.1f}", f"{max_w} pts", status_str])

            comp_table = Table(table_data, colWidths=[200, 100, 100, 140])
            comp_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#f8fafc')),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ]))
            story.append(comp_table)
            story.append(Spacer(1, 14))

        # 4. Target Job Description Keyword Match (If available)
        jd_data = data.get('jd_match_analysis') or data.get('jd_comparison')
        if hasattr(jd_data, 'model_dump'):
            jd_data = jd_data.model_dump()
        if isinstance(jd_data, dict) and jd_data:
            story.append(Paragraph("2. Job Description Match Analysis", h2_style))
            matched_kws = ", ".join(jd_data.get('matched_keywords', [])[:15]) or "None matched"
            missing_kws = ", ".join(jd_data.get('missing_keywords', [])[:15]) or "All key terms present"
            
            jd_table_data = [
                [Paragraph("<b>Matched Keywords:</b>", bold_body), Paragraph(matched_kws, body_style)],
                [Paragraph("<b>Missing Keywords:</b>", bold_body), Paragraph(missing_kws, body_style)],
            ]
            jd_table = Table(jd_table_data, colWidths=[140, 400])
            jd_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ]))
            story.append(jd_table)
            story.append(Spacer(1, 14))

        # 5. Detailed Actionable Recommendations & Issue Cards
        issues = data.get('detailed_feedback', [])
        if issues:
            story.append(Paragraph("3. Detailed Actionable Recommendations", h2_style))
            for item in issues:
                if not isinstance(item, dict) and hasattr(item, 'model_dump'):
                    item = item.model_dump()
                title = item.get('issue_title', item.get('title', 'Recommendation'))
                severity = item.get('severity_level', 'Medium').capitalize()
                explanation = item.get('explanation', '')
                how_to_fix = item.get('how_to_fix', '')

                story.append(Paragraph(f"• <b>{title}</b> — <font color='#b45309'>[{severity} Severity]</font>", bold_body))
                if explanation:
                    story.append(Paragraph(f"  {explanation}", body_style))
                if how_to_fix:
                    story.append(Paragraph(f"  <b>Action Item:</b> {how_to_fix}", fix_style))
                story.append(Spacer(1, 6))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes

